is_saving: true #動画やログを保存するかどうか
save_dir: "result" #result_local
case_name: "earth"
movie:
  fps: 50
  total_sec: 15

seed: 42

shader:
  vert: Phong.vert # 頂点シェーダパス
  frag: RichPhong2.frag # フラグメントシェーダパス

window_width: 1600
window_height: 900
