is_saving: false #動画やログを保存するかどうか
save_dir: "result_test" #result_local
case_name: ""
movie:
  fps: 50
  total_sec: 15
jsonl_save_interval_sec: 0.1

seed: 42

shader:
  vert: Phong.vert # 頂点シェーダパス
  frag: PhongRich.frag # フラグメントシェーダパス

window_width: 1600
window_height: 900
